In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2])

In [3]:
print("Array-1")
arr1

Array-1


array([1, 2])

In [4]:
arr2 = np.array([4,6])

In [5]:
print("Array-2")
arr2

Array-2


array([4, 6])

In [6]:
comb_arr = np.array(np.meshgrid(arr1,arr2)). T.reshape(-1,2)

In [7]:
print("Combination Array")
comb_arr

Combination Array


array([[1, 4],
       [1, 6],
       [2, 4],
       [2, 6]])