In [1]:
# How to create a empty and full numpy array
import numpy as np

arr1 = np.empty([3,3], dtype=int)
print("Empty array")
print(arr1)

arr2 = np.full([3,3],77,dtype=int)
print("Full array")
print(arr2)

Empty array
[[1663052921 1635020399 1852403305]
 [1616912487 1952539743  543187041]
 [ 543452769 1834967136 1617654625]]
Full array
[[77 77 77]
 [77 77 77]
 [77 77 77]]


In [2]:
arr1.ravel()

array([1663052921, 1635020399, 1852403305, 1616912487, 1952539743,
        543187041,  543452769, 1834967136, 1617654625])

In [3]:
arr2.ravel()

array([77, 77, 77, 77, 77, 77, 77, 77, 77])