In [1]:
# Check whether a Numpy array contains a specified row
import numpy as np

In [2]:
arr = np.array([[1,2,3,4,5],
               [6,7,8,9,1],
               [11,12,13,14,15],
               [16,17,18,19,20]])

In [3]:
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9  1]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [4]:
print([1, 2, 3, 4, 5] in arr.tolist())
print([6,7,-8,9,1] in arr.tolist())
print([11,77,13,14,15] in arr.tolist())
print([16,17,18,19,20] in arr.tolist())

True
False
False
True
