In [1]:
# Remove single dimensional entries from the shape of an array
import numpy as np

In [2]:
arr1 = np.array([[[2,2,2],[2,2,2]]])

In [3]:
print("Input array:- ", arr1)

Input array:-  [[[2 2 2]
  [2 2 2]]]


In [4]:
print("Shape of input array:- ", arr1.shape)

Shape of input array:-  (1, 2, 3)


In [5]:
out_arr1 = np.squeeze(arr1)

In [6]:
print("Output squeezed array:- ", out_arr1)

Output squeezed array:-  [[2 2 2]
 [2 2 2]]


In [7]:
print("Shape of squeezed array:- ", out_arr1.shape)

Shape of squeezed array:-  (2, 3)


In [8]:
arr2 = np.arange(9).reshape(1,3,3)

In [9]:
print("Input array:- ", arr2)

Input array:-  [[[0 1 2]
  [3 4 5]
  [6 7 8]]]


In [10]:
out_arr2 = np.squeeze(arr2, axis = 0)

In [11]:
print("Output array is:- ", out_arr2)

Output array is:-  [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
print("Shape of Input and Output array")
print(arr2.shape, out_arr2.shape)

Shape of Input and Output array
(1, 3, 3) (3, 3)
