In [1]:
import numpy as np

In [2]:
#This code will generate a single output only, it will not work fine if the array contains more than one element having the maximum number of frequency

arr = np.array([1,2,3,4,5,1,2,1,1,1])

In [3]:
print("Original array")
print(arr)

Original array
[1 2 3 4 5 1 2 1 1 1]


In [4]:
print("Most frequent value in the array")
print(np.bincount(arr).argmax())
print(np.bincount(arr).max())
print(np.bincount(arr)) # bicounts function counts the number of unique values in an array

Most frequent value in the array
1
5
[0 5 2 1 1 1]


In [5]:
# If the array contains more than one element having the maximum number of frequency

arr2 = np.array([1,1,1,2,3,4,2,4,3,3])

In [6]:
print("Original array")
print(arr2)

Original array
[1 1 1 2 3 4 2 4 3 3]


In [7]:
print("Most frequent value in the array")
x = np.bincount(arr2)
maximum = max(x)

for i in range(len(x)):
    if x[i] == maximum:
        print(i, end = " ")

Most frequent value in the array
1 3 