In [1]:
import numpy as np

In [2]:
arr1 = np.arange(5)
print("One Dimensional Array")
print(arr1)

One Dimensional Array
[0 1 2 3 4]


In [3]:
arr2 = np.arange(10).reshape(2,5)
print("Two Dimensional Array")
print(arr2)

Two Dimensional Array
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [4]:
for a, b in np.nditer([arr1, arr2]):
    print("%d:%d" % (a,b))

0:0
1:1
2:2
3:3
4:4
0:5
1:6
2:7
3:8
4:9
